services:
  backend:
    volumes:
      - ./backend:/app:delegated
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    environment:
      SQLALCHEMY_ECHO: "1" # Enable SQL query logging
